// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQGsyWvBHqKHyML4b9waHoRiHb1wJYQ6Q',
    appId: '1:253112803524:web:041b17a82b3bfb3210e991',
    messagingSenderId: '253112803524',
    projectId: 'mynotes-boobala',
    authDomain: 'mynotes-boobala.firebaseapp.com',
    storageBucket: 'mynotes-boobala.appspot.com',
    measurementId: 'G-QTY2SJYCHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA89GEflP1YxHYnQUTniVct-AsQubOcbDU',
    appId: '1:253112803524:android:8abc416eefeb038110e991',
    messagingSenderId: '253112803524',
    projectId: 'mynotes-boobala',
    storageBucket: 'mynotes-boobala.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd1d_dAJdD9SzJ5r0ZyRuMy5WwiYo_7gY',
    appId: '1:253112803524:ios:05ee2dedb9fc54ab10e991',
    messagingSenderId: '253112803524',
    projectId: 'mynotes-boobala',
    storageBucket: 'mynotes-boobala.appspot.com',
    iosBundleId: 'ru.irsdirect.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd1d_dAJdD9SzJ5r0ZyRuMy5WwiYo_7gY',
    appId: '1:253112803524:ios:bca1596f70741a1210e991',
    messagingSenderId: '253112803524',
    projectId: 'mynotes-boobala',
    storageBucket: 'mynotes-boobala.appspot.com',
    iosBundleId: 'ru.irsdirect.mynotes.RunnerTests',
  );
}
